### ISSUE TITLE
doesnt apply on recently updated elements in angular js

### ISSUE THREAD

**Issue by manoj529** [visionmedia/move.js#66]
I have used move.js along with angular.js and trying to add some animations to newly added elements.
when the elements are static it works fine.

Problem :
Now,when i try to add the same to newly scope elements it doesn't apply.I guess there would be some issue with the sequence of execution. 
As the move.js functions functions runs before my angular js updates the scope method.

so far, i tried :+1: 
1) Included it before body closing tag.
2) tried to get the regular jquery last element get function to identify the last element in the list(ie my newly added element) but it takes last but one element and applies my animations to that code.
 
Please let me know if i have any alternative or used any wrong approach.

Thank you in advance.

**Comment by laicosly** [comment]
You need to learn about angular directives.

**Comment by shuvalov-anton** [comment]
Looks like this question is better to ask on stackoverflow.
